name: equations_solver
description: An equation-solving application that uses the API of the 'equations' package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/application_ui
  - packages/equation_painter

dependencies:
  equations:
    path: ../../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/