name: equations
description: An equation-solving library that supports complex numbers.
version: 6.0.0
repository: https://github.com/albertodev01/equations
homepage: https://pub.dev/packages/equations

environment:
  sdk: ^3.10.4

dependencies:
  fraction: ^5.0.5
  petitparser: ^7.0.1

dev_dependencies:
  test: ^1.28.0

topics:
  - equations
  - numbers
  - algebra
