name: equations
description: An equation-solving library that supports complex numbers and fractions.
version: 6.0.0
repository: https://github.com/albertodev01/equations
homepage: https://pub.dev/packages/equations

environment:
  sdk: ^3.8.0

dependencies:
  fraction: ^5.0.5
  petitparser: ^7.0.0

dev_dependencies:
  test: ^1.25.15

topics:
  - equations
  - numbers
  - algebra
