name: equations
description: An equation-solving library that also works with complex numbers and fractions.
version: 5.0.2
repository: https://github.com/albertodev01/equations
homepage: https://pub.dev/packages/equations

environment:
  sdk: ^3.1.0

dependencies:
  fraction: ^5.0.2
  petitparser: ^5.4.0

dev_dependencies:
  test: ^1.24.6

topics:
  - equations
  - numbers
  - algebra