name: equations
description: An equation-solving library that also works with complex numbers and fractions.
version: 5.2.0
repository: https://github.com/albertodev01/equations
homepage: https://pub.dev/packages/equations

environment:
  sdk: ^3.6.0

dependencies:
  fraction: ^5.0.4
  petitparser: ^6.0.2

dev_dependencies:
  test: ^1.25.12

topics:
  - equations
  - numbers
  - algebra
