name: equations
description: An equation solving library written in Dart which also works with complex numbers and fractions.
version: 3.1.3
repository: https://github.com/albertodev01/equations
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/collection
  collection: ^1.15.0

  # https://pub.dev/packages/fraction
  fraction: ^3.2.1

  # https://pub.dev/packages/petitparser
  petitparser: ^4.4.0

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.0.4

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.8.1

  # https://pub.dev/packages/lints
  lints: ^1.0.1

  # https://pub.dev/packages/test
  test: ^1.20.1
  