name: equation_solver_cli
description: A Dart CLI application that uses the API of the 'equations' package.
version: 1.0.6
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equations:
    path: ../../

dev_dependencies:
  test: ^1.25.8
