name: equation_solver_cli
description: A sample command-line application.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equations:
    path: ../../

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.3.1

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.15.2

  # https://pub.dev/packages/test
  test: ^1.21.1
  