name: documentation_web_deploy

on:
  push:
    branches:
      - master

jobs:
  documentation_deployment:
    name: HTML Documentation deployment
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: dart pub get

      - name: Generating the documentation
        run: dart doc

      - name: Setting the git username
        run: git config user.name github-actions

      - name: Setting the git email
        run: git config user.email github-actions@github.com

      - name: Adding web source
        run: git --work-tree doc/api add --all

      - name: Adding a commit message
        run: git commit -m "Automatic deployment by github-actions"

      - name: Automatic web deployment
        run: git push origin HEAD:equations_doc --force
